#pragma once

/* 内嵌式配置页面资源，直接编译进固件，避免额外静态文件系统依赖。 */
static const char *HTML_INDEX =
"<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>ESP32C3 DTU</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:Arial,sans-serif;background:#1a1a2e;color:#e0e0e0;padding:10px}"
"h1{color:#00d4ff;text-align:center;padding:10px 0}"
"h2{color:#00b4d8;border-bottom:1px solid #333;padding:8px 0;margin:15px 0 10px}"
".card{background:#16213e;border-radius:8px;padding:15px;margin:10px 0}"
".row{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin:5px 0}"
"label{min-width:120px;color:#aaa;font-size:14px}"
"input,select{background:#0f3460;border:1px solid #333;color:#e0e0e0;padding:6px 10px;border-radius:4px;flex:1;min-width:150px;font-size:14px}"
"button{background:#00b4d8;color:#1a1a2e;border:none;padding:8px 20px;border-radius:4px;cursor:pointer;font-weight:bold;font-size:14px}"
"button:hover{background:#00d4ff}"
"button.danger{background:#e74c3c;color:#fff}"
"button.danger:hover{background:#c0392b}"
".status{display:flex;gap:15px;flex-wrap:wrap}"
".stat-item{background:#0f3460;padding:10px 15px;border-radius:6px;text-align:center;min-width:100px}"
".stat-val{font-size:20px;font-weight:bold;color:#00d4ff}"
".stat-lbl{font-size:12px;color:#888;margin-top:4px}"
"pre{background:#0f3460;padding:10px;border-radius:4px;overflow-x:auto;font-size:12px;max-height:300px;overflow-y:auto}"
".cb-row{display:flex;flex-wrap:wrap;gap:8px}"
".cb-item{background:#0f3460;padding:4px 10px;border-radius:4px;font-size:13px}"
".cb-item input{margin-right:4px;vertical-align:middle}"
"</style></head><body>"
"<h1>ESP32C3 DTU Config</h2>"

"<div class='card'><h2>System Status</h2>"
"<div class='status' id='status'>"
"<div class='stat-item'><div class='stat-val' id='st-wifi'>--</div><div class='stat-lbl'>WiFi</div></div>"
"<div class='stat-item'><div class='stat-val' id='st-net'>--</div><div class='stat-lbl'>Network</div></div>"
"<div class='stat-item'><div class='stat-val' id='st-temp'>--</div><div class='stat-lbl'>Temp(C)</div></div>"
"<div class='stat-item'><div class='stat-val' id='st-heap'>--</div><div class='stat-lbl'>FreeHeap</div></div>"
"<div class='stat-item'><div class='stat-val' id='st-uptime'>--</div><div class='stat-lbl'>Uptime(s)</div></div>"
"</div></div>"

"<div class='card'><h2>WiFi Config</h2>"
"<div class='row'><label>SSID</label><input id='wifi_ssid'></div>"
"<div class='row'><label>Password</label><input id='wifi_pass' type='password'></div>"
"<div class='row'><label>Mode</label><select id='wifi_mode'>"
"<option value='0'>AP</option><option value='1' selected>STA</option><option value='2'>APSTA</option></select></div></div>"

"<div class='card'><h2>Channel1 Config</h2>"
"<div class='row'><label>Socket1 IP</label><input id='srv1_ip'></div>"
"<div class='row'><label>Socket1 Port</label><input id='srv1_port' type='number'></div>"
"<div class='row'><label>Mode</label><select id='uart1_mode'>"
"<option value='0'>TCP</option><option value='1'>UDP</option><option value='2'>MQTT</option><option value='3'>HTTP</option></select></div>"
"<div class='row'><label>HTTP URL</label><input id='http_url1'></div>"
"<div class='row'><label>MQTT Pub</label><input id='mqtt_pub_topic1'></div>"
"<div class='row'><label>MQTT Sub</label><input id='mqtt_sub_topic1'></div></div>"

"<div class='card'><h2>Channel2 Config</h2>"
"<div class='row'><label>Socket2 IP</label><input id='srv2_ip'></div>"
"<div class='row'><label>Socket2 Port</label><input id='srv2_port' type='number'></div>"
"<div class='row'><label>Mode</label><select id='uart2_mode'>"
"<option value='0'>TCP</option><option value='1'>UDP</option><option value='2'>MQTT</option><option value='3'>HTTP</option></select></div>"
"<div class='row'><label>HTTP URL</label><input id='http_url2'></div>"
"<div class='row'><label>MQTT Pub</label><input id='mqtt_pub_topic2'></div>"
"<div class='row'><label>MQTT Sub</label><input id='mqtt_sub_topic2'></div></div>"

"<div class='card'><h2>UART1 Config (RS485-A)</h2>"
"<div class='row'><label>Baud Rate</label><input id='uart1_baud' type='number'></div>"
"<div class='row'><label>Parity</label><select id='uart1_parity'>"
"<option value='0'>None</option><option value='1'>Even</option><option value='2'>Odd</option></select></div>"
"<div class='row'><label>Stop Bits</label><select id='uart1_stop'>"
"<option value='1'>1</option><option value='2'>2</option></select></div></div>"

"<div class='card'><h2>UART2 Config (RS485-B)</h2>"
"<div class='row'><label>Baud Rate</label><input id='uart2_baud' type='number'></div>"
"<div class='row'><label>Parity</label><select id='uart2_parity'>"
"<option value='0'>None</option><option value='1'>Even</option><option value='2'>Odd</option></select></div>"
"<div class='row'><label>Stop Bits</label><select id='uart2_stop'>"
"<option value='1'>1</option><option value='2'>2</option></select></div></div>"

"<div class='card'><h2>MQTT Config</h2>"
"<div class='row'><label>Broker URI</label><input id='mqtt_broker'></div>"
"<div class='row'><label>Client ID</label><input id='mqtt_client_id'></div>"
"<div class='row'><label>Username</label><input id='mqtt_user'></div>"
"<div class='row'><label>Password</label><input id='mqtt_pass' type='password'></div>"
"<div class='row'><label>Use TLS</label><select id='mqtt_use_tls'>"
"<option value='0'>No</option><option value='1'>Yes</option></select></div></div>"

"<div class='card'><h2>PT1000 Calibration</h2>"
"<p>Connect a 1000-ohm resistor, then click Calibrate.</p>"
"<button onclick='calibrate()'>Calibrate (1000 ohm)</button></div>"

"<div class='card'><h2>OTA Update</h2>"
"<div class='row'><label>Firmware URL</label><input id='ota_url'></div>"
"<button onclick='startOta()'>Start OTA</button></div>"

"<div class='card'><h2>Blackbox Log</h2>"
"<button onclick='loadBlackbox()'>Refresh</button> <button class='danger' onclick='clearBlackbox()'>Clear</button>"
"<pre id='blackbox'>Click Refresh to load</pre></div>"

"<div class='card'><h2>Debug Log Control</h2>"
"<div class='cb-row' id='log-ctrl'>Loading...</div>"
"<button onclick='saveLogCtrl()' style='margin-top:8px'>Save</button></div>"

"<div class='card' style='text-align:center'>"
"<button onclick='saveConfig()'>Save All Config</button> "
"<button class='danger' onclick='restartDevice()'>Restart Device</button></div>"

"<script>"
"const MODS=['MAIN','WIFI','RS485','NET','WEB','BLE','PT1000','CMD','OTA','CONFIG','BLACKBOX'];"
"function api(m,u,d){return fetch(u,{method:m,headers:{'Content-Type':'application/json'},body:d?JSON.stringify(d):undefined}).then(r=>r.json())}"
"function numVal(id){let v=document.getElementById(id).value;return v===''?0:Number(v)}"

"function loadConfig(){api('GET','/api/v1/config').then(c=>{"
"for(let k in c){let e=document.getElementById(k);if(e)e.value=c[k]}})}"
"function saveConfig(){"
"let c={"
"wifi_ssid:document.getElementById('wifi_ssid').value,"
"wifi_pass:document.getElementById('wifi_pass').value,"
"wifi_mode:numVal('wifi_mode'),"
"srv1_ip:document.getElementById('srv1_ip').value,"
"srv1_port:numVal('srv1_port'),"
"srv2_ip:document.getElementById('srv2_ip').value,"
"srv2_port:numVal('srv2_port'),"
"uart1_mode:numVal('uart1_mode'),"
"uart2_mode:numVal('uart2_mode'),"
"uart1_baud:numVal('uart1_baud'),"
"uart1_parity:numVal('uart1_parity'),"
"uart1_stop:numVal('uart1_stop'),"
"uart2_baud:numVal('uart2_baud'),"
"uart2_parity:numVal('uart2_parity'),"
"uart2_stop:numVal('uart2_stop'),"
"mqtt_broker:document.getElementById('mqtt_broker').value,"
"mqtt_client_id:document.getElementById('mqtt_client_id').value,"
"mqtt_user:document.getElementById('mqtt_user').value,"
"mqtt_pass:document.getElementById('mqtt_pass').value,"
"mqtt_pub_topic1:document.getElementById('mqtt_pub_topic1').value,"
"mqtt_sub_topic1:document.getElementById('mqtt_sub_topic1').value,"
"mqtt_pub_topic2:document.getElementById('mqtt_pub_topic2').value,"
"mqtt_sub_topic2:document.getElementById('mqtt_sub_topic2').value,"
"mqtt_use_tls:numVal('mqtt_use_tls'),"
"http_url1:document.getElementById('http_url1').value,"
"http_url2:document.getElementById('http_url2').value,"
"ota_url:document.getElementById('ota_url').value"
"};"
"api('PUT','/api/v1/config',c).then(r=>{alert(r.status||'saved')})}"

"function loadStatus(){api('GET','/api/v1/status').then(s=>{"
"document.getElementById('st-wifi').textContent=s.wifi_status||'--';"
"document.getElementById('st-net').textContent=s.net_status||'--';"
"document.getElementById('st-heap').textContent=s.free_heap||'--';"
"document.getElementById('st-uptime').textContent=s.uptime||'--'});"
"api('GET','/api/v1/status/temperature').then(t=>{"
"document.getElementById('st-temp').textContent=t.temp_c!=null?t.temp_c.toFixed(2):'--'})}"

"function calibrate(){api('POST','/api/v1/calibrate',{ref_ohm:1000}).then(r=>alert(r.status||'done'))}"
"function startOta(){let u=document.getElementById('ota_url').value;if(!u)return alert('Enter URL');api('POST','/api/v1/ota',{url:u}).then(r=>alert(r.status||'started'))}"
"function loadBlackbox(){api('GET','/api/v1/blackbox?count=50').then(r=>{"
"document.getElementById('blackbox').textContent=(r.entries||[]).join('\\n')||'empty'})}"
"function clearBlackbox(){api('DELETE','/api/v1/blackbox').then(r=>{document.getElementById('blackbox').textContent='cleared'})}"

"function loadLogCtrl(){let h='';MODS.forEach(m=>{h+='<label class=\\'cb-item\\'><input type=\\'checkbox\\' id=\\'log_'+m+'\\' checked>'+m+'</label>'});"
"document.getElementById('log-ctrl').innerHTML=h;"
"api('GET','/api/v1/log_config').then(r=>{if(r.enabled)MODS.forEach(m=>{let e=document.getElementById('log_'+m);if(e)e.checked=r.enabled.includes(m)})})}"
"function saveLogCtrl(){let en=[];MODS.forEach(m=>{if(document.getElementById('log_'+m).checked)en.push(m)});"
"api('PUT','/api/v1/log_config',{enabled:en}).then(r=>alert('saved'))}"

"function restartDevice(){if(confirm('Restart device?'))api('POST','/api/v1/config/apply').then(()=>alert('restarting...'))}"

"loadConfig();loadStatus();loadLogCtrl();setInterval(loadStatus,5000);"
"</script></body></html>";
